!: BOLT #VERSION#
!: ALLOW CONCURRENT

A: HELLO {"{}": "*"}
*: RESET
{+
    {{
        C: RUN "RETURN 1 as n" {} {"mode": "r"}
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": 1000}
        S: FAILURE {"code": "Neo.ClientError.Security.AuthorizationExpired", "message": "Authorization expired"}
           <EXIT>
    ----
        C: RUN "RETURN 2 as n" {} {"mode": "r"}
        S: SUCCESS {"fields": ["n"]}
        {+
            C: PULL {"n": 1}
            S: RECORD [1]
               SUCCESS {"type": "r", "has_more": true}
        +}
        C: DISCARD {"n": -1}
        S: SUCCESS {}
    ----
        C: RUN "RETURN 3 as n" {} {"mode": "r"}
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": "*"}
        S: RECORD [1]
           SUCCESS {"type": "r"}
    ----
        C: BEGIN {"mode": "r"}
        S: SUCCESS {}

        {{
            C: RUN "TX RUN 1/3 ONE RECORD" {} {}
            S: SUCCESS {"fields": ["n"]}
            C: PULL {"n": "*"}
            S: RECORD [1]
               SUCCESS {"type": "r"}

            C: RUN "TX RUN 2/3 ONE RECORD" {} {}
            S: SUCCESS {"fields": ["n"]}
            C: PULL {"n": "*"}
            S: RECORD [1]
               SUCCESS {"type": "r"}

            C: RUN "TX RUN 3/3 ONE RECORD" {} {}
            S: SUCCESS {"fields": ["n"]}
            C: PULL {"n": "*"}
            S: RECORD [1]
               SUCCESS {"type": "r"}

            C: COMMIT
            S: SUCCESS {}
        ----
            C: RUN "TX RUN ONE RECORD" {} {}
            S: SUCCESS {"fields": ["n"]}
            C: PULL {"n": "*"}
            S: RECORD [1]
               SUCCESS {"type": "r"}
            C: COMMIT
            S: SUCCESS {}
        }}
    }}

    *: RESET
+}
?: GOODBYE
