!: BOLT #VERSION#
!: AUTO HELLO
!: AUTO RESET
!: ALLOW CONCURRENT

{+
    {{
        C: RUN "RETURN 1 as n" {} {"mode": "r"}
           PULL {"n": 1000}
        S: SUCCESS {"fields": ["n"]}
           FAILURE {"code": "Neo.ClientError.Security.AuthorizationExpired", "message": "Authorization expired"}
        S: <EXIT>
    ----
        C: RUN "RETURN 2 as n" {} {"mode": "r"}
        S: SUCCESS {"fields": ["n"]}
        {+
            C: PULL {"n": 1}
            S: RECORD [1]
               SUCCESS {"type": "r", "has_more": true}
        +}
        C: DISCARD {"n": -1}
        S: SUCCESS {}
    ----
        C: RUN "RETURN 3 as n" {} {"mode": "r"}
           PULL {"n": "*"}
        S: SUCCESS {"fields": ["n"]}
           RECORD [1]
           SUCCESS {"type": "r"}
    }}
+}
{?
    C: GOODBYE
    S: <EXIT>
?}
