!: BOLT #VERSION#
!: ALLOW RESTART

A: HELLO {"{}": "*"}
{{
   C: ROUTE #ROUTINGCTX# [] "adb"
   S: FAILURE #ERROR#
   *: RESET
   {*
      C: BEGIN {"mode": "r", "db": "adb"}
      S: SUCCESS {}
      C: RUN "RETURN 1 as n" {} {}
         PULL {"n": 1000}
      S: FAILURE #ERROR#
         <EXIT>
   *}
   ----
   {*
      C: BEGIN {"mode": "r", "db": "adb"}
      S: SUCCESS {}
      C: RUN "RETURN 1 as n" {} {}
         PULL {"n": 1000}
      S: SUCCESS {"fields": ["n"]}
         RECORD [1]
         SUCCESS {"type": "r"}
      C: COMMIT
      S: SUCCESS {}
      *: RESET
   *}
}}
*: RESET
?: GOODBYE