!: BOLT 4.4

A: HELLO {"{}": "*"}
*: RESET

{{
    C: RUN "RETURN 1 AS n" {} {#BM_IN#, "[mode]": "w"}
    S: SUCCESS {"fields": ["n"]}
    {{
        C: PULL {"n": {"Z": "*"}, "[qid]": -1}
    ----
        C: DISCARD {"n": {"Z": "*"}, "[qid]": -1}
    }}
    S: SUCCESS {"type": "w", "bookmark": "#BM_OUT#"}
----
    C: RUN "RETURN 1 AS n" {} {#BM_IN#, "mode": "r"}
    S: SUCCESS {"fields": ["n"]}
    {{
        C: PULL {"n": {"Z": "*"}, "[qid]": -1}
    ----
        C: DISCARD {"n": {"Z": "*"}, "[qid]": -1}
    }}
    S: SUCCESS {"type": "r", "bookmark": "#BM_OUT#"}
}}

*: RESET
?: GOODBYE
