!: BOLT 4
!: AUTO HELLO
!: AUTO RESET
!: AUTO GOODBYE

C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx42"]}
S: SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL {"n": 1000}
S: SUCCESS {"fields": ["name"]}
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx4242"}
C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx4242"]}
S: SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL {"n": 1000}
S: SUCCESS {"fields": ["name"]}
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx424242"}
