!: BOLT #VERSION#
!: AUTO RESET
!: ALLOW RESTART

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007", "routing": {"address": "#HOST#:9000"}, "[patch_bolt]": "*" #EXTRA_HELLO_PROPS#}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
{?
    C: ROUTE {"address": "#HOST#:9000"} [] "adb"
    S: SUCCESS { "rt": { "ttl": 1000, "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9000", "#HOST#:9011"], "role":"READ"}, {"addresses": ["#HOST#:9020", "#HOST#:9021"], "role":"WRITE"}]}}
    {?
        C: GOODBYE
        S: SUCCESS {}
           <EXIT>
    ?}
?}
C: BEGIN {"mode": "r", "db": "adb"}
S: SUCCESS {}
C: RUN "RETURN 1 as n" {} {}
S: SUCCESS {"fields": ["n"]}
C: PULL {"n": 1000}
S: RECORD [1]
   SUCCESS {"type": "r"}
C: COMMIT
S: SUCCESS {}
