!: BOLT #VERSION#
!: AUTO RESET
!: AUTO GOODBYE

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007", "routing": #ROUTINGCTX# #EXTRA_HELLO_PROPS#}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
C: BEGIN {"db": "system"}
C: RUN "CREATE database foo" {} {}
S: SUCCESS {}
C: PULL {"n": 1000}
S: SUCCESS {"fields": []}
S: SUCCESS {"type": "w"}
C: COMMIT
S: SUCCESS {"bookmark": "SystemBookmark"}
C: RUN "RETURN 1 as n" {} {"db": "adb", "bookmarks": ["SystemBookmark"]}
C: PULL {"n": 1000}
S: SUCCESS {"fields": ["n"]}
   RECORD [1]
   SUCCESS {"type": "r"}
