!: BOLT #VERSION#

A: HELLO {"{}": "*"}
*: RESET
C: BEGIN {"db": "adb", "bookmarks": ["BookmarkA"]}
S: SUCCESS {}
C: RUN "CREATE (n {name:'Bob'})" {} {}
   PULL {"n": 1000}
S: SUCCESS {"fields": ["name"]}
   SUCCESS {"type": "w"}
C: COMMIT
S: SUCCESS {"bookmark": "BookmarkB"}
*: RESET
C: BEGIN {"db": "adb", "bookmarks": ["BookmarkB"]}
S: SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL {"n": 1000}
S: SUCCESS {"fields": ["name"]}
   RECORD ["Bob"]
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "BookmarkC"}
*: RESET
?: GOODBYE
