!: BOLT 4.4

A: HELLO {"{}": "*"}
*: RESET
{{
    C: ROUTE {"{}": "*"} null {"[db]": null, "[imp_user]": null}
----
    C: ROUTE {"{}": "*"} [] {"[db]": null, "[imp_user]": null}
}}
S: SUCCESS {"rt": {"ttl": 1000, "db": "homedb", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010", "#HOST#:9020", "#HOST#:9030", "#HOST#:9040", "#HOST#:9050"], "role":"READ"}, {"addresses": ["#HOST#:9060"], "role":"WRITE"}]}}
*: RESET
?: GOODBYE
