!: BOLT 5.2

A: HELLO {"[user_agent]": "*", "[routing]": "*", "[noti_min_sev]": "WARNING", "[noti_dis_cats]":["UNSUPPORTED", "UNRECOGNIZED", "DEPRECATION", "HINT"]}
A: LOGON {"{}": "*"}
*: RESET
C: BEGIN {#NOTIS#"[mode]": "*", "[db]": "*"}
S: SUCCESS {}
C: RUN "RETURN 1 as n" {} {}
S: SUCCESS {"fields": ["n"]}
{{
    C: PULL "*"
----
    C: DISCARD "*"
}}
S: SUCCESS {"type": "r"}
C: COMMIT
S: SUCCESS {}
*: RESET
?: GOODBYE
