!: BOLT 5.2

A: HELLO {"[user_agent]": "*", "[routing]": "*", "notifications_minimum_severity": "WARNING", "notifications_disabled_categories":["UNSUPPORTED", "UNRECOGNIZED", "DEPRECATION", "HINT"]}
A: LOGON {"{}": "*"}
*: RESET
C: RUN "RETURN 1 as n" {} {#NOTIS#"[mode]": "*", "[db]": "*"}
S: SUCCESS {"fields": ["n"]}
{{
    C: PULL "*"
    S: RECORD [1]
----
    C: DISCARD "*"
}}
S: SUCCESS {"type": "r"}
*: RESET
?: GOODBYE
