!: BOLT 5.8

C: HELLO {"{}": "*"}
S: SUCCESS {"connection_id": "bolt-1", "server": "Neo4j/5.26.0"}
A: LOGON {"{}": "*"}
*: RESET

{+
    C: RUN {"U": "*"} {} {"db": "homedb1", "[bookmarks]": {"[]": "*"}, "mode": "r"}
    S: SUCCESS {"fields": ["n"]}
    {{
        C: PULL {"n": {"Z": "*"}, "[qid]": -1}
        S: RECORD [1]
    ----
        C: DISCARD {"n": {"Z": "*"}, "[qid]": -1}
    }}
    S: SUCCESS {}
    *: RESET
+}

?: GOODBYE
