!: BOLT 5.8
!: ALLOW CONCURRENT

A: HELLO {"{}": "*"}
A: LOGON {"{}": "*"}
*: RESET

{*
    C: ROUTE "*" "*" {"db": "homedb1"}
    S: SUCCESS { "rt": { "ttl": 1000000, "db": "homedb1", "servers": [{"addresses": ["#HOST#:9000"], "role": "ROUTE"}, {"addresses": ["#HOST#:9010"], "role": "READ"}, {"addresses": ["#HOST#:9020"], "role": "WRITE"}]}}
    *: RESET
*}

{+
    C: ROUTE "*" "*" {"[db]": ""}
    S: SUCCESS { "rt": { "ttl": 1000000, "db": "homedb1", "servers": [{"addresses": ["#HOST#:9000"], "role": "ROUTE"}, {"addresses": ["#HOST#:9010"], "role": "READ"}, {"addresses": ["#HOST#:9020"], "role": "WRITE"}]}}
    *: RESET

    {*
        C: ROUTE "*" "*" {"db": "homedb1"}
        S: SUCCESS { "rt": { "ttl": 1000000, "db": "homedb1", "servers": [{"addresses": ["#HOST#:9000"], "role": "ROUTE"}, {"addresses": ["#HOST#:9010"], "role": "READ"}, {"addresses": ["#HOST#:9020"], "role": "WRITE"}]}}
        *: RESET
    *}
+}

?: GOODBYE
