!: BOLT 5.8

A: HELLO {"{}": "*"}
A: LOGON {"{}": "*"}
*: RESET

{*
    {{
        C: RUN "RESOLVED" {} {"db": "homedb1", "[bookmarks]": {"[]": "*"}, "[mode]": "w"}
        S: SUCCESS {"fields": ["n"]}
    ----
        C: RUN "UNRESOLVED" {} {"[bookmarks]": {"[]": "*"}, "[mode]": "w"}
        S: SUCCESS {"fields": ["n"], "db": "homedb1"}
    }}
    {{
        C: PULL {"n": {"Z": "*"}, "[qid]": -1}
        S: RECORD [1]
    ----
        C: DISCARD {"n": {"Z": "*"}, "[qid]": -1}
    }}
    S: SUCCESS {}
    *: RESET
*}

?: GOODBYE
