!: BOLT 4.4
!: ALLOW CONCURRENT

C: HELLO {"{}": "*"}
S: SUCCESS {"server": "Neo4j/4.4.1", "hints": {"ssr.enabled": 1}, "connection_id": "bolt-1"}
*: RESET

C: BEGIN {"[tx_metadata]": "*", "mode": "r", "imp_user": "the-imposter"}
S: SUCCESS {}
C: RUN "RETURN 1" {} {}
S: SUCCESS {"fields": ["1"]}
C: PULL {"n": {"Z": "*"}, "[qid]": -1}
S: RECORD [1]
S: SUCCESS {"type": "r"}
C: COMMIT
S: SUCCESS {"db": "homedb1"}
*: RESET

C: BEGIN {"[tx_metadata]": "*", "mode": "r", "imp_user": "the-imposter"}
S: SUCCESS {}
C: RUN "RETURN 2" {} {}
S: SUCCESS {"fields": ["2"]}
C: PULL {"n": {"Z": "*"}, "[qid]": -1}
S: RECORD [2]
S: SUCCESS {"type": "r"}
C: COMMIT
S: SUCCESS {"db": "homedb1"}
*: RESET

C: BEGIN {"[tx_metadata]": "*", "mode": "r", "imp_user": "the-imposter"}
S: SUCCESS {}
C: RUN "RETURN 3" {} {}
S: SUCCESS {"fields": ["3"]}
C: PULL {"n": {"Z": "*"}, "[qid]": -1}
S: RECORD [3]
S: SUCCESS {"type": "r"}
C: COMMIT
S: SUCCESS {"db": "homedb3"}
*: RESET

C: BEGIN  {"[bookmarks]": "*", "[tx_metadata]": "*", "mode": "r", "imp_user": "the-imposter"}
S: SUCCESS {}
C: RUN "RETURN 4" {} {}
S: SUCCESS {"fields": ["4"]}
C: PULL {"n": {"Z": "*"}, "[qid]": -1}
S: RECORD [4]
S: SUCCESS {"type": "r"}
C: COMMIT
S: SUCCESS {"db": "homedb3"}

*: RESET
?: GOODBYE
