!: BOLT 4.4
!: ALLOW CONCURRENT

A: HELLO {"{}": "*"}
*: RESET
{+
    {{
        C: BEGIN {"[tx_metadata]": "*", "mode": "r", "imp_user": "the-imposter"}
        S: SUCCESS {}
        C: RUN "RETURN 1" {} {}
        S: SUCCESS {"fields": ["1"]}
        {{
            C: PULL {"n": {"Z": "*"}, "[qid]": -1}
            S: RECORD [1]
        ----
            C: DISCARD {"n": {"Z": "*"}, "[qid]": -1}
        }}
    ----
        C: BEGIN  {"[bookmarks]": "*", "[tx_metadata]": "*", "mode": "r", "imp_user": "the-imposter"}
        S: SUCCESS {}
        C: RUN "RETURN 2" {} {}
        S: SUCCESS {"fields": ["2"]}
        {{
            C: PULL {"n": {"Z": "*"}, "[qid]": -1}
            S: RECORD [2]
        ----
            C: DISCARD {"n": {"Z": "*"}, "[qid]": -1}
        }}
    }}
    S: SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {"db": "homedb"}
    *: RESET
+}
?: GOODBYE
