!: BOLT 4.4
!: ALLOW RESTART

A: HELLO {"{}": "*"}
*: RESET
{*
    {{
        C: RUN "RETURN 1" {} {"[bookmarks]": "*", "[tx_metadata]": "*", "mode": "r", "imp_user": "the-imposter", "db": "homedb1"}
        S: SUCCESS {"fields": ["1"]}
        C: PULL {"n": 1000}
        S: RECORD [1]
           SUCCESS {"type": "r"}
    ----
        C: RUN "RETURN 2" {} {"[bookmarks]": "*", "[tx_metadata]": "*", "mode": "r", "imp_user": "the-imposter", "db": "homedb2"}
        S: SUCCESS {"fields": ["2"]}
        C: PULL {"n": 1000}
        S: RECORD [2]
           SUCCESS {"type": "r"}
    }}
    *: RESET
*}
?: GOODBYE
