[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 2
use_parentheses = true
ensure_newline_before_comments = true

[tool.yapf]
based_on_style = "pep8"
COALESCE_BRACKETS = true
DEDENT_CLOSING_BRACKETS = true
INDENT_DICTIONARY_VALUE = true
SPLIT_BEFORE_ARITHMETIC_OPERATOR = true
SPLIT_BEFORE_DOT = true
SPLIT_BEFORE_EXPRESSION_AFTER_OPENING_PAREN = true
SPLIT_BEFORE_FIRST_ARGUMENT = true
SPLIT_COMPLEX_COMPREHENSION = true
