[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 2
use_parentheses = true
ensure_newline_before_comments = true
order_by_type = false
remove_redundant_aliases = true
force_sort_within_sections = true

[tool.flake8]
inline-quotes = "double"

# [tool.yapf]
# based_on_style = "pep8"
# COALESCE_BRACKETS = true
# ALIGN_CLOSING_BRACKET_WITH_VISUAL_INDENT = true
# DEDENT_CLOSING_BRACKETS = false
# INDENT_DICTIONARY_VALUE = true
# SPLIT_BEFORE_ARITHMETIC_OPERATOR = true
# SPLIT_BEFORE_DOT = true
# SPLIT_BEFORE_EXPRESSION_AFTER_OPENING_PAREN = true
# SPLIT_BEFORE_FIRST_ARGUMENT = false
# SPLIT_COMPLEX_COMPREHENSION = true
