!: BOLT #VERSION#

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007", "routing": #ROUTINGCTX#}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
*: RESET
C: RUN "CALL dbms.routing.getRoutingTable($context, $database)" {"context": #ROUTINGCTX#, "[database]": "*"} {"[mode]": "r", "db": "system", "bookmarks": ["foobar"]}
S: FAILURE {"code": "Neo.ClientError.Request.Invalid", "message": "Kaboooom."}
{?
    C: PULL {"n": {"Z": "*"}}
    S: IGNORED
?}
*: RESET
?: GOODBYE
