!: BOLT #VERSION#
!: AUTO RESET
!: AUTO GOODBYE

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007", "routing": #ROUTINGCTX# #EXTRA_HELLO_PROPS# }
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
{{
    C: RUN "CALL dbms.routing.getRoutingTable($context, $database)" {"context": #ROUTINGCTX#, "database": "*"} {"[mode]": "r", "db": "system", "[bookmarks]": "*"}
----
    C: RUN "CALL dbms.routing.getRoutingTable($context)" {"context": #ROUTINGCTX#} {"[mode]": "r", "db": "system", "[bookmarks]": "*"}
}}
C: PULL {"n": -1}
S: FAILURE {"code": "Neo.ClientError.General.Unknown", "message": "wut!"}
   IGNORED
   <EXIT>
