!: BOLT #VERSION#
!: AUTO RESET
!: AUTO GOODBYE

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007", "routing": #ROUTINGCTX# #EXTRA_HELLO_PROPS# }
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
{{
    C: RUN "CALL dbms.routing.getRoutingTable($context)" {"context": #ROUTINGCTX#} {"[mode]": "r", "db": "system"}
----
    C: RUN "CALL dbms.routing.getRoutingTable($context, $database)" {"context": #ROUTINGCTX#, "database": null} {"[mode]": "r", "db": "system"}
----
    C: RUN "CALL dbms.routing.getRoutingTable($context, $database)" {"context": #ROUTINGCTX#, "database": "system"} {"[mode]": "r", "db": "system"}
}}
C: PULL {"n": -1}
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [1000, [{"addresses": ["#HOST#:9001"], "role":"ROUTE"}, {"addresses": ["#HOST#:9100"], "role":"READ"}, {"addresses": ["#HOST#:9020", "#HOST#:9022"], "role":"WRITE"}]]
   SUCCESS {"type": "r"}
   <EXIT>
