!: BOLT #VERSION#
!: ALLOW CONCURRENT

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007", "routing": #ROUTINGCTX#}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
*: RESET
{?
    C: RUN "CALL dbms.routing.getRoutingTable($context, $database)" {"context": #ROUTINGCTX#, "database": "adb"} {"[mode]": "r", "db": "system", "[bookmarks]": "*"}
    S: SUCCESS {"fields": ["ttl", "servers"]}
    C: PULL {"n": -1}
    S: RECORD [1000, [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010", "#HOST#:9011"], "role":"READ"}, {"addresses": ["#HOST#:9000"], "role":"WRITE"}]]
       SUCCESS {"type": "r"}
?}
*: RESET
{?
    C: RUN "RETURN 1 as n" {} {"db": "adb"}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": 1000}
    S: SUCCESS {"type": "w", "bookmark": "NewBookmark"}
    *: RESET
    C: RUN "RETURN 1 as n" {} {"db": "adb", "bookmarks": ["NewBookmark"]}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": 1000}
    S: RECORD [1]
       SUCCESS {"type": "r"}
?}
*: RESET
?: GOODBYE
