!: BOLT #VERSION#

A: HELLO {"{}": "*"}
A: LOGON {"scheme": "basic", "principal": "neo4j", "credentials": "pass"}
*: RESET

C: ROUTE #ROUTINGCTX# [] {}
S: SUCCESS {"rt": {"ttl": 1000, "db": "adb", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

*: RESET

C: ROUTE #ROUTINGCTX# [] {}
S: SUCCESS {"rt": {"ttl": 1000, "db": "adb", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

*: RESET
A: LOGOFF
A: LOGON {"scheme": "basic", "principal": "neo5j", "credentials": "pass++"}
*: RESET

C: ROUTE #ROUTINGCTX# [] {}
S: SUCCESS {"rt": {"ttl": 1000, "db": "adb", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

*: RESET

C: ROUTE #ROUTINGCTX# [] {}
S: SUCCESS {"rt": {"ttl": 1000, "db": "adb", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

*: RESET
?: GOODBYE
