!: BOLT #VERSION#

C: HELLO {"user_agent": "*", "[routing]": null}
C: LOGON {"scheme": "bearer", "credentials": "QmFuYW5hIQ==", "[principal]": "", "[realm]": ""}
S: SUCCESS {"connection_id": "bolt-0", "server": "Neo4j/#VERSION#.0", "routing": null}
S: SUCCESS {}
*: RESET

C: RUN "RETURN 1 AS n" "*" "*"
S: SUCCESS {"fields": ["n"]}
C: PULL "*"
S: RECORD [1]
   SUCCESS {"type": "r"}

*: RESET
?: GOODBYE
