!: BOLT #VERSION#

# Server versions pre 4.4 require empty principal field. So for backwards compatibility, we expect the driver to send it.
A: HELLO {"scheme": "kerberos", "principal": "", "credentials": "QmFuYW5hIQ==", "[realm]": ""} {"user_agent": "*", "[routing]": null}
*: RESET

C: RUN "RETURN 1 AS n" "*" "*"
S: SUCCESS {"fields": ["n"]}
C: PULL "*"
S: RECORD [1]
   SUCCESS {"type": "r"}

*: RESET
?: GOODBYE
