!: BOLT #VERSION#

A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}}
A: LOGON {"scheme": "basic", "principal": "neo4j", "credentials": "pass"}

*: RESET

C: RUN "RETURN 1 AS n" "*" "*"
S: SUCCESS {"fields": ["n"]}
C: PULL "*"
S: RECORD [1]
   SUCCESS {"type": "w"}

*: RESET

# reader fails now with Neo.ClientError.Security.TokenExpired => this connection should also be re-authenticated
A: LOGOFF
A: LOGON {"scheme": "basic", "principal": "neo4j", "credentials": "password"}

*: RESET

C: RUN "RETURN 2 AS n" "*" "*"
S: SUCCESS {"fields": ["n"]}
C: PULL "*"
S: RECORD [1]
   SUCCESS {"type": "w"}

*: RESET
?: GOODBYE
