!: BOLT #VERSION#

A: HELLO {"user_agent": "*", "[routing]": "*"}
A: LOGON {"scheme": "basic", "principal": "neo4j", "credentials": "pass", "[realm]": ""}

*: RESET

C: RUN "RETURN 1 AS n" "*" "*"
S: SUCCESS {"fields": ["n"]}
C: PULL "*"
S: RECORD [1]
   SUCCESS {"type": "w"}

# reader fails now with #ERROR#
# => this connection to a different host should not be affected
*: RESET

C: RUN "RETURN 2 AS n" "*" "*"
S: SUCCESS {"fields": ["n"]}
C: PULL "*"
S: RECORD [1]
   SUCCESS {"type": "w"}

*: RESET
?: GOODBYE
