!: BOLT 4.3
!: ALLOW RESTART

A: HELLO {"{}": "*"}
*: RESET

{?
    C: RUN "QUERY 1" "*" "*"
    S: SUCCESS {"fields": ["1"]}
    C: PULL "*"
    S: RECORD [1]
       RECORD [1]
       SUCCESS {"has_more": true}
    C: DISCARD "*"
    S: SUCCESS {"type": "#TYPE#"}
    *: RESET
?}

C: RUN "QUERY 2" "*" "*"
S: SUCCESS {"fields": ["1"]}
C: PULL "*"
S: RECORD [2]
   RECORD [2]
   SUCCESS {"has_more": true}
C: DISCARD "*"
S: SUCCESS {"type": "#TYPE#"}

*: RESET
?: GOODBYE
