!: BOLT 4

A: HELLO {"{}": "*"}
C: BEGIN {}
S: SUCCESS {}
C: RUN "RETURN 1" {} {}
S: SUCCESS {}
C: PULL {"n": 1000}
S: FAILURE {"code": "#ERROR#", "message": "<whatever>"}
C: RESET
S: SUCCESS {}
#EXTRA_RESET_1#
C: BEGIN {}
S: SUCCESS {}
C: RUN "RETURN 1" {} {}
S: SUCCESS {"fields": ["n"]}
C: PULL {"n": 1000}
S: RECORD [1]
   SUCCESS {"type": "r"}
C: COMMIT
S: SUCCESS {}
#EXTRA_RESET_2#
?: GOODBYE
