!: BOLT #VERSION#
!: AUTO RESET
!: AUTO HELLO


C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": #ROUTINGCTX#} {"[mode]": "r"}
S: SUCCESS {"fields": ["ttl", "servers"]}
C: PULL_ALL
S: RECORD [1000, [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": [], "role":"READ"}, {"addresses": ["#HOST#:9000"], "role":"WRITE"}]]
   SUCCESS {"type": "r"}
{?
    C: GOODBYE
    S: <EXIT>
?}
