!: BOLT #VERSION#

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007" #EXTRA_HELLO_PROPS# #EXTR_HELLO_ROUTING_PROPS#}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
*: RESET
C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": #ROUTINGCTX#} {"[mode]": "r"}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [1000, []]
   SUCCESS {"type": "r"}
   <EXIT>
