!: BOLT #VERSION#
!: AUTO HELLO
!: AUTO GOODBYE
!: AUTO RESET
!: ALLOW RESTART

C: BEGIN {}
S: SUCCESS {}
{{
    C: RUN "RETURN 1.1 as n" {} {}
    S: FAILURE {"code": "Neo.ClientError.Cluster.NotALeader", "message": "blabla"}
    {?
        C: PULL_ALL
        S: IGNORED
    ?}
    {?
        # Driver that keep the connection alive after NotALeader will take this
        # path.
        C: BEGIN {}
        S: SUCCESS {}
        C: RUN "RETURN 2.1 as n" {} {}
        S: SUCCESS {"fields": ["n"]}
        C: PULL_ALL
        S: RECORD [1]
           SUCCESS {"type": "w"}
        C: RUN "RETURN 2.2 as n" {} {}
        S: SUCCESS {"fields": ["n"]}
        C: PULL_ALL
        S: RECORD [1]
           SUCCESS {"type": "w"}
        C: COMMIT
        S: SUCCESS {}
    ?}
----
    # Driver that closes the connection after NotALeader will take this path
    # after a reconnect.
    C: RUN "RETURN 2.1 as n" {} {}
    S: SUCCESS {"fields": ["n"]}
    C: PULL_ALL
    S: RECORD [1]
       SUCCESS {"type": "w"}
    C: RUN "RETURN 2.2 as n" {} {}
    S: SUCCESS {"fields": ["n"]}
    C: PULL_ALL
    S: RECORD [1]
       SUCCESS {"type": "w"}
    C: COMMIT
    S: SUCCESS {}
}}
