!: BOLT #VERSION#
!: ALLOW RESTART

A: HELLO {"{}": "*"}
*: RESET
C: BEGIN {}
S: SUCCESS {}
{{
    C: RUN "RETURN 1.1 as n" {} {}
       PULL_ALL
    S: FAILURE {"code": "Neo.ClientError.Cluster.NotALeader", "message": "blabla"}
       IGNORED
    *: RESET
    {?
        # Driver that keep the connection alive after NotALeader will take this
        # path.
        C: BEGIN {}
        S: SUCCESS {}
        C: RUN "RETURN 2.1 as n" {} {}
           PULL_ALL
        S: SUCCESS {"fields": ["n"]}
           RECORD [1]
           SUCCESS {"type": "w"}
        C: RUN "RETURN 2.2 as n" {} {}
           PULL_ALL
        S: SUCCESS {"fields": ["n"]}
           RECORD [1]
           SUCCESS {"type": "w"}
        C: COMMIT
        S: SUCCESS {}
    ?}
----
    # Driver that closes the connection after NotALeader will take this path
    # after a reconnect.
    C: RUN "RETURN 2.1 as n" {} {}
       PULL_ALL
    S: SUCCESS {"fields": ["n"]}
       RECORD [1]
       SUCCESS {"type": "w"}
    C: RUN "RETURN 2.2 as n" {} {}
       PULL_ALL
    S: SUCCESS {"fields": ["n"]}
       RECORD [1]
       SUCCESS {"type": "w"}
    C: COMMIT
    S: SUCCESS {}
}}
*: RESET
?: GOODBYE
