!: BOLT #VERSION#

A: HELLO {"{}": "*"}
*: RESET
C: BEGIN {"bookmarks": ["BookmarkA"]}
S: SUCCESS {}
C: RUN "CREATE (n {name:'Bob'})" {} {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "BookmarkB"}
*: RESET
C: BEGIN {"bookmarks": ["BookmarkB"]}
S: SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["name"]}
   RECORD ["Bob"]
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "BookmarkC"}
*: RESET
?: GOODBYE
