!: BOLT #VERSION#
!: AUTO HELLO
!: AUTO GOODBYE
!: AUTO RESET

C: BEGIN {"bookmarks{}": ["neo4j:bookmark:v1:tx5", "neo4j:bookmark:v1:tx29", "neo4j:bookmark:v1:tx94", "neo4j:bookmark:v1:tx56", "neo4j:bookmark:v1:tx16", "neo4j:bookmark:v1:tx68"]}
S: SUCCESS {}
C: RUN "RETURN 1 as n" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["n"]}
   SUCCESS {"type": "w"}
C: COMMIT
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx95"}
