!: BOLT #VERSION#
!: AUTO HELLO
!: AUTO GOODBYE
!: AUTO RESET

C: BEGIN {}
S: SUCCESS {}
C: RUN "RETURN 1 as n" {} {}
   PULL_ALL
S: FAILURE {"code": "Neo.ClientError.Cluster.NotALeader", "message": "blabla"}
   IGNORED
C: BEGIN {}
S: SUCCESS {}
C: RUN "RETURN 1 as n" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["n"]}
   RECORD [1]
   SUCCESS {"type": "w"}
C: RUN "RETURN 1 as n" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["n"]}
   RECORD [1]
   SUCCESS {"type": "w"}
C: COMMIT
S: SUCCESS {}
