!: BOLT 4

A: HELLO {"{}": "*"}
*: RESET

C: BEGIN {"{}": "*"}
S: SUCCESS {}
C: RUN "*" "*" "*"
S: SUCCESS {"fields": ["n"]}
{{
    # No PULL pipelining
    # Calling result.next
    C: PULL {"n": 2}
    S: RECORD [1]
       RECORD [2]
       SUCCESS {"has_more": true}
    # Calling result.list
    C: PULL {"n": -1}
    S: RECORD [3]
       RECORD [4]
       RECORD [5]
----
    # Pipelining PULL
    C: PULL {"n": 2}
    S: RECORD [1]
       RECORD [2]
       SUCCESS {"has_more": true}
    # Calling result.next
    C: PULL {"n": 2}
    S: RECORD [3]
       RECORD [4]
       SUCCESS {"has_more": true}
    # Calling result.list
    C: PULL {"n": -1}
    S: RECORD [5]
}}
S: SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "bm"}

*: RESET
?: GOODBYE
