!: BOLT #VERSION#
!: AUTO GOODBYE

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "#USER_AGENT#" #ROUTING# #EXTRA_HELLO_PROPS#}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
C: BEGIN {"db": "adb"}
S: SUCCESS {}
{{
    C: RUN "RETURN 1 as n" {} {}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": 1000}
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: ROLLBACK
    S: FAILURE {"code": "Neo.TransientError.General.DatabaseUnavailable", "message": "Unable to rollback"}
    C: RESET
    S: SUCCESS {}
    {?
        C: RESET
        S: SUCCESS {}
    ?}
----
    C: RUN "RETURN 5 as n" {} {}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": 1000}
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: FAILURE {"code": "Neo.TransientError.General.DatabaseUnavailable", "message": "Unable to commit"}
    C: RESET
    S: SUCCESS {}
    {?
        C: RESET
        S: SUCCESS {}
    ?}
----
    C: RUN "RETURN 7 as n" {} {}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": 1000}
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: FAILURE {"code": "Neo.TransientError.General.DatabaseUnavailable", "message": "Database shut down."}
       <EXIT>
}}
