!: BOLT #VERSION#

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "#USER_AGENT#" #ROUTING#}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
*: RESET
{{
    C: RUN "RETURN 1 as n" {} {"db": "adb"}
    S: SUCCESS {"fields": ["n"]}
    C: PULL { "n": -1 }
    S: RECORD [1]
       RECORD [5]
       RECORD [7]
       SUCCESS {}
----
    C: RUN "RETURN 5 as n" {} {"db": "adb"}
    S: SUCCESS {"fields": ["n"]}
    C: PULL { "n": 1000 }
    S: <NOOP>
       RECORD [1]
       <NOOP>
       RECORD [5]
       <NOOP>
       <NOOP>
       RECORD [7]
       SUCCESS {}
}}
*: RESET
?: GOODBYE
