!: BOLT #VERSION#

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007", "routing": #ROUTINGCTX#, "[patch_bolt]": "*"}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
*: RESET
C: ROUTE #ROUTINGCTX# ["foobar"] {"[db]": "*"}
S: FAILURE {"code": "Neo.ClientError.Security.MadeUpSecurityError", "message": "I don't know what happened; it's classified as top secret :/"}
*: RESET
?: GOODBYE
