!: BOLT #VERSION#

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007", "routing": #ROUTINGCTX#, "[patch_bolt]": "*"}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
*: RESET
C: ROUTE #ROUTINGCTX# ["foobar"] {"[db]": "*"}
S: FAILURE {"code": "Neo.ClientError.Transaction.InvalidBookmark", "message": "Supplied bookmarks 'foobar' does not conform to pattern {database_id}:{tx_id}."}
*: RESET
?: GOODBYE
