!: BOLT 3
!: AUTO HELLO
!: ALLOW RESTART

{*
    C: RESET
    S: SUCCESS {}
*}

{?
    C: RUN "QUERY 1" "*" "*"
    S: SUCCESS {"fields": ["1"]}
    C: PULL_ALL
    S: RECORD [1]
       SUCCESS {"type": "#TYPE#"}

    {*
        C: RESET
        S: SUCCESS {}
    *}
?}

C: RUN "QUERY 2" "*" "*"
S: SUCCESS {"fields": ["1"]}
C: PULL_ALL
S: RECORD [2]
   SUCCESS {"type": "#TYPE#"}

{*
    C: RESET
    S: SUCCESS {}
*}
{?
    C: GOODBYE
    S: <EXIT>
?}
