!: BOLT 5.8
!: ALLOW CONCURRENT

A: HELLO {"{}": "*"}

{+
    {{
        A: LOGON {"scheme": "basic", "principal": "*", "credentials": "*", "[realm]": "*"}
        *: RESET

        {*
            {{
                {{
                    C: BEGIN {"[db]": null, "[bookmarks]": ["db1"], "mode": "r"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["db1"], "mode": "r"}
                ----
                    C: BEGIN {"[db]": null, "[bookmarks]": ["router-db2-reader-db1"], "mode": "r"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["router-db2-reader-db1"], "mode": "r"}
                }}
                S: SUCCESS {"db": "db1"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["admin1@homedb1@#SERVER_NAME#"]
            ----
                {{
                    C: BEGIN {"bookmarks": ["db2"], "mode": "r"}
                ----
                    C: BEGIN {"bookmarks": ["router-db1-reader-db2"], "mode": "r"}
                }}
                S: SUCCESS {"db": "db2"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["admin1@homedb2@#SERVER_NAME#"]
            ----
                C: BEGIN {"[bookmarks]": "*", "db": "db1", "mode": "r"}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["admin1@db1@#SERVER_NAME#"]
            ----
                C: BEGIN {"[bookmarks]": "*", "db": "db2", "mode": "r"}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["admin1@db2@#SERVER_NAME#"]

            ----

                {{
                    C: BEGIN {"[db]": null, "[bookmarks]": ["db1"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["db1"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"[db]": null, "[bookmarks]": ["router-db2-reader-db1"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["router-db2-reader-db1"], "mode": "r", "imp_user": "user1"}
                }}
                S: SUCCESS {"db": "db1"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user1@homedb1@#SERVER_NAME#"]
            ----
                {{
                    C: BEGIN {"[db]": null, "bookmarks": ["db2"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"db": "", "bookmarks": ["db2"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"[db]": null, "bookmarks": ["router-db1-reader-db2"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"db": "", "bookmarks": ["router-db1-reader-db2"], "mode": "r", "imp_user": "user1"}
                }}
                S: SUCCESS {"db": "db2"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user1@homedb2@#SERVER_NAME#"]

            ----

                {{
                    C: BEGIN {"[db]": null, "bookmarks": ["db1"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"db": "", "bookmarks": ["db1"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"[db]": null, "bookmarks": ["router-db2-reader-db1"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"db": "", "bookmarks": ["router-db2-reader-db1"], "mode": "r", "imp_user": "user2"}
                }}
                S: SUCCESS {"db": "db1"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user2@homedb1@#SERVER_NAME#"]
            ----
                {{
                    C: BEGIN {"[db]": null, "[bookmarks]": ["db2"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["db2"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"[db]": null, "[bookmarks]": ["router-db1-reader-db2"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["router-db1-reader-db2"], "mode": "r", "imp_user": "user2"}
                }}
                S: SUCCESS {"db": "db2"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user2@homedb2@#SERVER_NAME#"]

            ----

                {{
                    C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "db1", "imp_user": "user1"}
                ----
                    C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "router-db2-reader-db1", "imp_user": "user1"}
                }}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user1@db1@#SERVER_NAME#"]
            ----
                {{
                    C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "db2", "imp_user": "user1"}
                ----
                    C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "router-db1-reader-db2", "imp_user": "user1"}
                }}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user1@db2@#SERVER_NAME#"]
            ----
                {{
                    C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "db1", "imp_user": "user2"}
                ----
                    C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "router-db2-reader-db1", "imp_user": "user2"}
                }}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user2@db1@#SERVER_NAME#"]
            ----
                {{
                    C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "db2", "imp_user": "user2"}
                ----
                    C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "router-db1-reader-db2", "imp_user": "user2"}
                }}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user2@db2@#SERVER_NAME#"]
            }}

            S: SUCCESS {}
            C: COMMIT
            S: SUCCESS {"type": "r"}
            *: RESET
        *}

    ----

        A: LOGON {"scheme": "special", "[principal]": "*", "[credentials]": "*", "[realm]": "*", "[parameters]": "*"}
        *: RESET

        {*
            {{
                {{
                    C: BEGIN {"bookmarks": ["db1"], "mode": "r"}
                ----
                    C: BEGIN {"bookmarks": ["router-db2-reader-db1"], "mode": "r"}
                }}
                S: SUCCESS {"db": "db1"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["admin2@homedb1@#SERVER_NAME#"]
            ----
                {{
                    C: BEGIN {"[db]": null, "[bookmarks]": ["db2"], "mode": "r"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["db2"], "mode": "r"}
                ----
                    C: BEGIN {"[db]": null, "[bookmarks]": ["router-db1-reader-db2"], "mode": "r"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["router-db1-reader-db2"], "mode": "r"}
                }}
                S: SUCCESS {"db": "db2"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["admin2@homedb2@#SERVER_NAME#"]
            ----
                C: BEGIN {"[bookmarks]": "*", "db": "db1", "mode": "r"}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["admin2@db1@#SERVER_NAME#"]
            ----
                C: BEGIN {"[bookmarks]": "*", "db": "db2", "mode": "r"}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["admin2@db2@#SERVER_NAME#"]

            ----

                {{
                    C: BEGIN {"[db]": null, "[bookmarks]": ["db1"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["db1"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"[db]": null, "[bookmarks]": ["router-db2-reader-db1"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["router-db2-reader-db1"], "mode": "r", "imp_user": "user1"}
                }}
                S: SUCCESS {"db": "db1"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user1@homedb1@#SERVER_NAME#"]
            ----
                {{
                    C: BEGIN {"[db]": null, "bookmarks": ["db2"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"db": "", "bookmarks": ["db2"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"[db]": null, "bookmarks": ["router-db1-reader-db2"], "mode": "r", "imp_user": "user1"}
                ----
                    C: BEGIN {"db": "", "bookmarks": ["router-db1-reader-db2"], "mode": "r", "imp_user": "user1"}
                }}
                S: SUCCESS {"db": "db2"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user1@homedb2@#SERVER_NAME#"]

            ----

                {{
                    C: BEGIN {"[db]": null, "bookmarks": ["db1"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"db": "", "bookmarks": ["db1"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"[db]": null, "bookmarks": ["router-db2-reader-db1"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"db": "", "bookmarks": ["router-db2-reader-db1"], "mode": "r", "imp_user": "user2"}
                }}
                S: SUCCESS {"db": "db1"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user2@homedb1@#SERVER_NAME#"]
            ----
                {{
                    C: BEGIN {"[db]": null, "[bookmarks]": ["db2"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["db2"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"[db]": null, "[bookmarks]": ["router-db1-reader-db2"], "mode": "r", "imp_user": "user2"}
                ----
                    C: BEGIN {"db": "", "[bookmarks]": ["router-db1-reader-db2"], "mode": "r", "imp_user": "user2"}
                }}
                S: SUCCESS {"db": "db2"}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user2@homedb2@#SERVER_NAME#"]

            ----

                C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "db1", "imp_user": "user1"}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user1@db1@#SERVER_NAME#"]
            ----
                C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "db2", "imp_user": "user1"}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user1@db2@#SERVER_NAME#"]
            ----
                C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "db1", "imp_user": "user2"}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user2@db1@#SERVER_NAME#"]
            ----
                C: BEGIN {"[bookmarks]": "*", "mode": "r", "db": "db2", "imp_user": "user2"}
                S: SUCCESS {}
                C: RUN "WHOAMI" {} {}
                S: SUCCESS {"fields": ["YOU"]}
                C: PULL {"n": {"Z": "*"}, "[qid]": -1}
                S: RECORD ["user2@db2@#SERVER_NAME#"]
            }}

            S: SUCCESS {}
            C: COMMIT
            S: SUCCESS {"type": "r"}
            *: RESET
        *}
    }}
    ?: LOGOFF
+}

?: GOODBYE
