!: BOLT 5.8
!: ALLOW CONCURRENT
!: PY first_auth = True

A: HELLO {"{}": "*"}

{+
    IF: not first_auth
    {{
        A: LOGOFF
    }}

    {{
        A: LOGON {"scheme": "basic", "principal": "*", "credentials": "*", "[realm]": "*"}
        PY: first_auth = False
        *: RESET

        {*
            {{
                {{
                    C: ROUTE "*" [] {"db": "db1", "[imp_user]": "*", "[bookmarks]": "*"}
                ----
                    C: ROUTE "*" [] {"imp_user": "user1", "[bookmarks]": ["db1"]}
                ----
                    C: ROUTE "*" [] {"bookmarks": ["db1"], "[imp_user]": "*"}
                ----
                    C: ROUTE "*" [] {"[db]": null}
                ----
                    C: ROUTE "*" [] {"db": ""}
                }}
                S: SUCCESS { "rt": { "ttl": 1000000, "db": "db1", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9010"], "role":"WRITE"}]}}
            ----
                {{
                    C: ROUTE "*" [] {"db": "db2", "[imp_user]": "*", "[bookmarks]": "*"}
                ----
                    C: ROUTE "*" [] {"imp_user": "user2", "[bookmarks]": ["db2"]}
                ----
                    C: ROUTE "*" [] {"bookmarks": ["db2"], "[imp_user]": "*"}
                }}
                S: SUCCESS { "rt": { "ttl": 1000000, "db": "db2", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9011"], "role":"READ"}, {"addresses": ["#HOST#:9011"], "role":"WRITE"}]}}
            }}

            *: RESET
        *}

    ----

        A: LOGON {"scheme": "special", "[principal]": "*", "[credentials]": "*", "[realm]": "*", "[parameters]": "*"}
        PY: first_auth = False
        *: RESET

        {*
            {{
                {{
                    C: ROUTE "*" [] {"db": "db1", "[imp_user]": "*", "[bookmarks]": "*"}
                ----
                    C: ROUTE "*" [] {"imp_user": "user1", "[bookmarks]": ["db1"]}
                ----
                    C: ROUTE "*" [] {"bookmarks": ["db1"], "[imp_user]": "*"}
                }}
                S: SUCCESS { "rt": { "ttl": 1000000, "db": "db1", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9010"], "role":"WRITE"}]}}
            ----
                {{
                    C: ROUTE "*" [] {"db": "db2", "[imp_user]": "*", "[bookmarks]": "*"}
                ----
                    C: ROUTE "*" [] {"imp_user": "user2", "[bookmarks]": ["db2"]}
                ----
                    C: ROUTE "*" [] {"bookmarks": ["db2"], "[imp_user]": "*"}
                ----
                    C: ROUTE "*" [] {"[db]": null}
                ----
                    C: ROUTE "*" [] {"db": ""}
                }}
                S: SUCCESS { "rt": { "ttl": 1000000, "db": "db2", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9011"], "role":"READ"}, {"addresses": ["#HOST#:9011"], "role":"WRITE"}]}}
            }}

            *: RESET
        *}
    }}
+}

?: GOODBYE
