!: BOLT #VERSION#
!: ALLOW RESTART

{{
    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", "principal": "neo4j", "credentials": "pass", "[realm]": ""}
    *: RESET

    C: BEGIN {"mode": "r", "db": "adb"}
    S: SUCCESS {}
    C: RUN "RETURN 1 AS n" {} {}
    S: FAILURE {"code": "Neo.ClientError.Security.TokenExpired", "message": "Token expired."}
    S: <EXIT>
----
    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", "principal": "neo5j", "credentials": "pass++", "[realm]": ""}
    *: RESET

    C: BEGIN {"mode": "r", "db": "adb"}
    S: SUCCESS {}
    C: RUN "RETURN 2 AS n" {} {}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": {"Z": "*"}}
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {}

    *: RESET
    ?: GOODBYE
}}
