!: BOLT 6.0

C: HELLO {"{}": "*"}
S: SUCCESS {"server": "Neo4j/2026.0.0", "connection_id": "bolt-1", "hints": {"telemetry.enabled": true}}
A: LOGON {"{}": "*"}
*: RESET
C: TELEMETRY {"Z": "*"}
S: FAILURE {"neo4j_code": "Neo.ClientError.MadeUp.Idempotent", "message": "Something went wrong, but nothing's broken", "diagnostic_record": {"_idempotent": true}, "gql_status": "gql_status", "description": "description" }
{?
    C: RUN {"U": "*"} {"{}": "*"} {"{}": "*"}
    S: IGNORED
    {?
        # For drivers that pipeline a PULL after RUN
        C: PULL {"n": {"Z": "*"}}
        S: IGNORED
    ?}
?}
+: RESET
?: GOODBYE
