!: BOLT 6.0

A: HELLO {"{}": "*"}
A: LOGON {"{}": "*"}
*: RESET
C: RUN {"U": "*"} {"{}": "*"} {"{}": "*"}
S: FAILURE {"neo4j_code": "Neo.ClientError.MadeUp.Quick", "message": "Something went wrong, but nothing's broken", "diagnostic_record": { "_idempotent": true}, "gql_status": "gql_status", "description": "description" }
{?
    # For drivers that pipeline a PULL after RUN
    C: PULL {"n": {"Z": "*"}}
    S: IGNORED
?}
+: RESET
C: RUN {"U": "*"} {"{}": "*"} {"{}": "*"}
S: SUCCESS {"fields": ["n"]}
C: PULL {"n": {"Z": "*"}}
S: RECORD [1]
   SUCCESS {"type": "r"}
*: RESET
?: GOODBYE
