!: BOLT 6.0

C: HELLO {"{}": "*"}
S: SUCCESS {"server": "Neo4j/2026.0.0", "connection_id": "bolt-1", "hints": {"telemetry.enabled": true}}
*: RESET
A: LOGON {"{}": "*"}
C: TELEMETRY {"Z": "2"}
S: SUCCESS {}
C: RUN {"U": "*"} {"{}": "*"} {"{}": "*"}
S: FAILURE {"neo4j_code": "Neo.ClientError.MadeUp.Idempotent", "message": "Something went wrong, but nothing's broken", "diagnostic_record": { "_idempotent": true} }
{?
    # For drivers that pipeline a PULL after RUN
    C: PULL {"n": {"Z": "*"}}
    S: IGNORED
?}
?: RESET
C: RUN {"U": "*"} {"{}": "*"} {"{}": "*"}
S: FAILURE {"neo4j_code": "Neo.ClientError.MadeUp.Code", "message": "Something went wrong...", "diagnostic_record": { "_idempotent": true} }
{?
    # For drivers that pipeline a PULL after RUN
    C: PULL {"n": {"Z": "*"}}
    S: IGNORED
?}
+: RESET
?: GOODBYE
