!: BOLT #VERSION#
!: ALLOW CONCURRENT

A: HELLO {"{}": "*"}
*: RESET
C: BEGIN {"db": "adb"}
S: SUCCESS {}
{{
    C: RUN "RETURN 1 as n" {} {}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": 1000}
    S: SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {}
    *: RESET
    {?
        C: BEGIN {"db": "adb"}
        S: SUCCESS {}
        C: RUN "RETURN 1 as n" {} {}
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": 1000}
        S: SUCCESS {"type": "r"}
        C: COMMIT
        S: SUCCESS {}
        *: RESET
    ?}
    ?: GOODBYE
----
    C: RUN "RETURN 5 as n" {} {}
    S: <EXIT>
}}
