!: BOLT 4.4
!: AUTO HELLO
!: AUTO GOODBYE

{*
    C: RESET
    S: SUCCESS {}
*}
C: BEGIN {"{}": "*"}
S: SUCCESS {}
C: RUN {"U": "*"}{"{}": "*"} {"{}": "*"}
S: SUCCESS {"fields": ["n"]}
{+
    C: PULL {"n": {"Z": "*"}, "[qid]": -1}
    S: RECORD [1]
       RECORD [2]
       SUCCESS {"type": "r", "has_more": true}
+}
C: DISCARD {"n": -1, "[qid]": -1}
S: SUCCESS {}
C: ROLLBACK
S: SUCCESS {}
{*
    C: RESET
    S: SUCCESS {}
*}
