!: BOLT 5.3

A: HELLO {"{}": "*"}
A: LOGON {"{}": "*"}
*: RESET
C: BEGIN {"{}": "*"}
S: SUCCESS {}
C: RUN "RETURN 1 AS n" {"{}": "*"} {"{}": "*"}
S: SUCCESS {"fields": ["n"], "qid": 1}
{?
    {{
        C: PULL {"n": {"Z": "*"}, "[qid]": -1}
    ----
        C: PULL {"n": {"Z": "*"}, "qid": 1}
    }}
    S: RECORD [1]
       RECORD [2]
       SUCCESS {"has_more": true}
?}
C: RUN "invalid" {"{}": "*"} {"{}": "*"}
S: FAILURE {"code": "Neo.ClientError.Statement.SyntaxError", "message": "Invalid input"}
{?
    C: PULL {"n": {"Z": "*"}, "[qid]": -1}
    S: IGNORED
?}
+: RESET
?: GOODBYE
