!: BOLT #VERSION#
!: ALLOW RESTART

A: HELLO {"{}": "*"}
{{
   C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": #ROUTINGCTX#} {"[mode]": "r"}
      PULL_ALL
   S: SUCCESS {"fields": ["ttl", "servers"]}
      FAILURE #ERROR#
   *: RESET
   {*
      C: BEGIN {"mode": "r"}
      S: SUCCESS {}
      C: RUN "RETURN 1 as n" {} {}
         PULL_ALL
      S: FAILURE #ERROR#
         <EXIT>
   *}
   ----
   {*
      C: BEGIN {"mode": "r"}
      S: SUCCESS {}
      C: RUN "RETURN 1 as n" {} {}
         PULL_ALL
      S: SUCCESS {"fields": ["n"]}
         RECORD [1]
         SUCCESS {"type": "r"}
      C: COMMIT
      S: SUCCESS {}
      *: RESET
   *}
}}
*: RESET
?: GOODBYE