!: BOLT #VERSION#

A: HELLO {"{}": "*"}
C: BEGIN {"mode": "r"}
S: SUCCESS {}
{{
    C: RUN "RETURN 1 as n" {} {}
    S: SUCCESS {"fields": ["n"]}
    C: PULL_ALL
    S: RECORD [1]
       SUCCESS {"type": "r"}
----
    C: RUN "RETURN 5 as n" {} {}
    S: SUCCESS {"fields": ["n"]}
    {{
        C: PULL_ALL
        S: RECORD [1]
           SUCCESS {"type": "r"}
    ----
        C: DISCARD {"n": -1}
        S: SUCCESS {}
    }}
}}
C: COMMIT
S: FAILURE #ERROR#
   <EXIT>
