!: BOLT #VERSION#
!: ALLOW RESTART

A: HELLO {"{}": "*"}
{*
  *: RESET
  C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": #ROUTINGCTX#} {"[mode]": "r"}
     PULL_ALL
  S: SUCCESS {"fields": ["ttl", "servers"]}
     RECORD [1000, [{"addresses": ["#HOST#:9010"], "role":"ROUTE"}, {"addresses": ["#HOST#:9000"], "role":"READ"}, {"addresses": ["#HOST#:9020", "#HOST#:9021"], "role":"WRITE"}]]
     SUCCESS {"type": "r"}
  *: RESET
*}
?: GOODBYE
