!: BOLT 5.6
!: ALLOW CONCURRENT
!: PY request = 0

C: HELLO {"{}": "*"}
S: SUCCESS {"server": "Neo4j/5.21.0", "connection_id": "bolt-123456789"}
A: LOGON {"{}": "*"}

*: RESET

{*
    {{
        C: ROUTE {"address": "foo:9001"} [] {"db": "neo4j"}
        PY: request += 1
        IF: request == 1
        {{
            S: <EXIT>
        }}
        ELSE:
        {{
            S: SUCCESS { "rt": { "ttl": 1, "db": "neo4j", "servers": [{"addresses": ["foo:9001"], "role":"ROUTE"}, {"addresses": ["127.0.0.3:9001"], "role":"READ"}, {"addresses": ["127.0.0.3:9001"], "role":"WRITE"}]}}
        }}
    ----
        ?: TELEMETRY {"{}": "*"}
        C: BEGIN {"{}": "*"}
        PY: request = 0
        S: SUCCESS {}
        C: RUN "RETURN 1 AS n" {"{}": "*"} {"{}": "*"}
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": {"Z": "*"}}
        S: RECORD [1]
        S: SUCCESS {"type": "r"}
        C: COMMIT
        S: SUCCESS {}
    }}
    *: RESET
*}

?: GOODBYE
