!: BOLT 4.4
!: AUTO HELLO
!: AUTO GOODBYE
!: AUTO RESET

C: RUN "*" "*" "*"
S: SUCCESS {"t_first": 2001, "fields": ["n"]}
C: PULL {"n": "*"}
S: RECORD [1]
   SUCCESS {"type": "r", "db": "apple", "t_last": 2002, "stats": {"constraints-added": 1001, "constraints-removed": 1002, "indexes-added": 1003, "indexes-removed": 1004, "labels-added": 1005, "labels-removed": 1006, "nodes-created": 1007, "nodes-deleted": 1008, "properties-set": 1009, "relationships-created": 1010, "relationships-deleted": 1011, "system-updates": 1012}}
