!: BOLT 5.0
!: AUTO RESET
!: ALLOW RESTART

C: HELLO {"{}": "*"}
S: <SLEEP> 2
   <NOOP>
   <SLEEP> 2
   SUCCESS {"server": "Neo4j/5.0.0", "connection_id": "bolt-123456789"}
*: RESET
{+
    C: ROUTE "*" "*" "*"
    S: SUCCESS { "rt": { "ttl": 1000, "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9010"], "role":"WRITE"}]}}
    *: RESET
+}
?: GOODBYE
