!: BOLT 5.0
!: ALLOW CONCURRENT

A: HELLO {"{}": "*"}
*: RESET
{*
    {{
        C: RUN "QUERY1" "*" "*"
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": 1000}
        S: SUCCESS {"type": "r", "bookmark": "bm1"}
    ----
        C: RUN "QUERY2" "*" "*"
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": 1000}
        S: SUCCESS {"type": "r", "bookmark": "bm2"}
    ----
        C: RUN "QUERY3" "*" "*"
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": 1000}
        S: SUCCESS {"type": "r", "bookmark": "bm3"}
    ----
        C: RUN "USE adb QUERY2" "*" "*"
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": 1000}
        S: SUCCESS {"type": "r", "bookmark": "adb:bm4", "db": "adb"}
    }}
    *: RESET
*}

?: GOODBYE
