!: BOLT 4.3

A: HELLO {"{}": "*"}
*: RESET
# Impersonation is not a feature that bolt 4.3 supports. However, this server
# understands it anyway. This way, we can check that the driver raises the
# problem even before contacting the server.
C: BEGIN {"imp_user": "that-other-dude", "db": "homedb"}
S: SUCCESS {}
C: RUN "RETURN 1 as n" {} {}
S: SUCCESS {"fields": ["n"]}
C: PULL {"n": 1000}
S: SUCCESS {"type": "r"}
C: COMMIT
S: SUCCESS {}
*: RESET
?: GOODBYE
