[package]
name = "boltstub"
version = "0.1.0"
edition = "2021"
rust-version = "1.88.0"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
chrono-tz = "0.10.4"
clap = { version = "4.5.57", features = ["derive"] }
constcat = "0.6.1"
derive_more = { version = "2.1.1", features = ["display"] }
fern = { version = "0.7.1" }
indexmap = "2.13.0"
indoc = "2.0.7"
itertools = "0.14.0"
log = "0.4.29"
nom = "8.0.0"
nom_locate = "5.0.0"
pyo3 = "0.29.0"
regex = "1.12.3"
serde = "1.0.228"
serde_json = { version = "1.0.149", features = ["default", "preserve_order"] }
termcolor = "1.4.1"
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = "0.7.18"
usize_cast = "1.1.0"
pin-project = "1.1.10"
sha1 = "0.10.6"
base64 = "0.22.1"
uuid = "1.23.1"
rstest_reuse = "0.7.0"

[dev-dependencies]
rstest = "0.26.1"
