!: BOLT #VERSION#
!: PY warm = False
!: ALLOW CONCURRENT

IF: not warm
{{
    PY: warm = True

    # warmup connection
    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", #DRIVER_AUTH#, "[realm]": ""}
    *: RESET

    C: RUN "TESTKIT WARMUP" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": {"Z": "*"}}
    S: RECORD [1]
       SUCCESS {"type": "r"}

    *: RESET
    ?: GOODBYE
}}
ELSE:
{{
    # auth check query
    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", #VERIFY_AUTH#, "[realm]": ""}
    *: RESET

    # optionally, run dummy queries
    {*
        C: RUN {"U": "*"} "*" "*"
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": {"Z": "*"}}
        S: RECORD [1]
           SUCCESS {"type": "r"}

        *: RESET
    *}

    # enforce GOODBYE as this is a throwaway connection
    A: GOODBYE
}}
