!: BOLT #VERSION#
!: ALLOW RESTART

A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", "principal": {"U": "*"}, "credentials": {"U": "*"}, "[realm]": ""}
*: RESET

{*
    C: ROUTE {"{}": "*"} [] {"{}": {"db": "system"}}
    S: SUCCESS {"rt": {"ttl": 1000, "db": "system", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

    *: RESET
*}

?: GOODBYE
