!: BOLT #VERSION#
!: PY warm = False
!: ALLOW CONCURRENT

IF: not warm
{{
    PY: warm = True

    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", #DRIVER_AUTH#, "[realm]": ""}
    *: RESET

    C: ROUTE {"{}": "*"} [] {"{}": {"db": "system"}}
    S: SUCCESS {"rt": {"ttl": 1000, "db": "system", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

    *: RESET
    ?: GOODBYE
}}
ELSE:
{{
    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", #DRIVER_AUTH#, "[realm]": ""}
    S: FAILURE {"code": "#ERROR#", "message": "These are not the credentials you're looking for."}
       <EXIT>
}}
