!: BOLT #VERSION#
A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", "principal": "neo4j", "credentials": "pass", "[realm]": ""}
*: RESET

C: ROUTE {"{}": "*"} [] {"{}": {"db": "system"}}
S: SUCCESS {"rt": {"ttl": 1000, "db": "system", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

A: LOGOFF
C: LOGON {"scheme": "basic", "principal": "neo5j", "credentials": "pass++", "[realm]": ""}
S: FAILURE {"code": "#ERROR#", "message": "These are not the credentials you're looking for."}
   <EXIT>
