!: BOLT 3
!: AUTO HELLO
!: AUTO RESET

C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx42"]}
S: SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["name"]}
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx4242"}
C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx4242"]}
S: SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["name"]}
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx424242"}
{?
    C: GOODBYE
    S: <EXIT>
?}
