!: BOLT #VERSION#
!: ALLOW RESTART

{{
    A: HELLO {"user_agent": "*", "[routing]": "*", "scheme": "basic", "principal": "neo4j", "credentials": "pass"}

    *: RESET

    C: RUN "RETURN 1 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}

    *: RESET

    {?
       C: BEGIN {"{}": "*"}
       S: SUCCESS {}
    ?}

    C: RUN "RETURN 2 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}

    # auth info expired, a new connection is required
----
    A: HELLO {"user_agent": "*", "[routing]": "*", "scheme": "basic", "principal": "neo5j", "credentials": "pass++"}

    *: RESET

    C: RUN "RETURN 3 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}

    *: RESET

    C: RUN "RETURN 4 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}


}}

*: RESET
?: GOODBYE
