!: BOLT #VERSION#
!: ALLOW CONCURRENT

{{
    A: HELLO {"user_agent": "*", "[routing]": "*", "scheme": "basic", "principal": "neo4j", "credentials": "pass", "[realm]": ""}
    # connection 1 for session 1 and 4 with driver level auth
    *: RESET

    C: RUN "RETURN 1 AS n" {"{}": "*"} {"{}": "*"}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": {"Z": "*"}}
    S: RECORD [1]
       SUCCESS {"type": "r"}

    *: RESET

    C: RUN "RETURN 4 AS n" {"{}": "*"} {"{}": "*"}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": {"Z": "*"}}
    S: RECORD [1]
       SUCCESS {"type": "r"}

    *: RESET
    ?: GOODBYE
----
    A: HELLO {"user_agent": "*", "[routing]": "*", "scheme": "basic", "principal": "neo5j", "credentials": "pass++", "[realm]": ""}
    *: RESET

    {{
        # connection 2 for session 2 with session level auth
        C: RUN "RETURN 2 AS n" {"{}": "*"} {"{}": "*"}
    ----
        # connection 3 for session 3 with session level auth
        C: RUN "RETURN 3 AS n" {"{}": "*"} {"{}": "*"}
    }}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": {"Z": "*"}}
    S: RECORD [1]
       SUCCESS {"type": "r"}

    *: RESET
    # driver is expected to close the "throwaway" connection when the session is closed.
    # the beauty of the backwards compatibility layer /s
    A: GOODBYE
}}
