!: BOLT #VERSION#

A: HELLO {"{}": "*"}
*: RESET

C: RUN "RETURN 1 AS n" {"{}": "*"} {"{}": "*"}
S: SUCCESS {"fields": ["n"]}
C: PULL {"n": {"Z": "*"}}
S: RECORD [1]
   SUCCESS {"type": "r"}

*: RESET

C: RUN "RETURN 2 AS n" {"{}": "*"} {"{}": "*"}
S: SUCCESS {"fields": ["n"]}
C: PULL {"n": {"Z": "*"}}
S: RECORD [1]
   SUCCESS {"type": "r"}

*: RESET

C: RUN "RETURN 3 AS n" {"{}": "*"} {"{}": "*"}
S: SUCCESS {"fields": ["n"]}
C: PULL {"n": {"Z": "*"}}
S: RECORD [1]
   SUCCESS {"type": "r"}

*: RESET

C: RUN "RETURN 4 AS n" {"{}": "*"} {"{}": "*"}
S: SUCCESS {"fields": ["n"]}
C: PULL {"n": {"Z": "*"}}
S: RECORD [1]
   SUCCESS {"type": "r"}

*: RESET
?: GOODBYE
