!: BOLT #VERSION#
!: ALLOW CONCURRENT

A: HELLO {"user_agent": "*", "[routing]": "*", "scheme": "basic", "principal": "neo4j", "credentials": "pass", "[realm]": ""}

*: RESET

C: BEGIN {"{}": "*"}
S: SUCCESS {}
# Three concurrent connections
{{
    C: RUN "RETURN 1.1 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {}

    # now the second connection receives the error
    # => this connection should not be affected
    *: RESET

    C: BEGIN {"{}": "*"}
    S: SUCCESS {}
    C: RUN "RETURN 1.2 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {}
----
    C: RUN "RETURN 2.1 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {}

    *: RESET

    C: RUN "RETURN 2.2 AS n" "*" "*"
    S: FAILURE #ERROR#
    S: <EXIT>
----
    C: RUN "RETURN 2.3 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {}
----
    C: RUN "RETURN 3.1 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {}

    # now the second connection receives the error
    # => this connection should not be affected
    *: RESET

    C: BEGIN {"{}": "*"}
    S: SUCCESS {}
    C: RUN "RETURN 3.2 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {}
}}

*: RESET
?: GOODBYE
