!: BOLT #VERSION#
!: ALLOW CONCURRENT

{{
    # connection 1 and 4
    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", "principal": "neo4j", "credentials": "pass"}
    *: RESET
    {{
        # connection 1 for session 1 with session level auth
        C: RUN "RETURN 1 AS n" {"{}": "*"} {"{}": "*"}
    ----
        # connection 4 for session 4 with session level auth
        C: RUN "RETURN 4 AS n" {"{}": "*"} {"{}": "*"}
    }}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": {"Z": "*"}}
    S: RECORD [1]
       SUCCESS {"type": "r"}

    *: RESET
    # driver is expected to close the "throwaway" connection when the session is closed.
    # the beauty of the backwards compatibility layer /s
    A: GOODBYE
----
    # connection 2 for session 2 and 3 with driver level auth
    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", "principal": "neo5j", "credentials": "pass++"}
    *: RESET

    C: RUN "RETURN 2 AS n" {"{}": "*"} {"{}": "*"}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": {"Z": "*"}}
    S: RECORD [1]
       SUCCESS {"type": "r"}

    *: RESET

    C: RUN "RETURN 3 AS n" {"{}": "*"} {"{}": "*"}
    S: SUCCESS {"fields": ["n"]}
    C: PULL {"n": {"Z": "*"}}
    S: RECORD [1]
       SUCCESS {"type": "r"}

    *: RESET
    ?: GOODBYE
}}
