!: BOLT #VERSION#
!: ALLOW CONCURRENT

{{
    # connection for sessions with driver level auth (re-using connection)
    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", "principal": "neo4j", "credentials": "pass"}
    *: RESET

    C: ROUTE {"{}": "*"} {"[]": "*"} {"{}": "*"}
    S: SUCCESS {"rt": {"ttl": 1000, "db": "adb", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

    *: RESET

    C: ROUTE {"{}": "*"} {"[]": "*"} {"{}": "*"}
    S: SUCCESS {"rt": {"ttl": 1000, "db": "adb", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

    *: RESET
    ?: GOODBYE
----
    # connections for sessions with session level auth
    A: HELLO {"user_agent": "*", "[routing]": {"{}": "*"}, "scheme": "basic", "principal": "neo5j", "credentials": "pass++"}
    *: RESET

    C: ROUTE {"{}": "*"} {"[]": "*"} {"{}": "*"}
    S: SUCCESS {"rt": {"ttl": 1000, "db": "adb", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

    *: RESET
    # driver is expected to close the "throwaway" connection when the session is closed.
    # the beauty of the backwards compatibility layer /s
    A: GOODBYE
}}
