!: BOLT #VERSION#
!: ALLOW RESTART

{{
    A: HELLO {"user_agent": "*", "[routing]": "*", "scheme": "basic", "principal": "neo4j", "credentials": "pass", "[realm]": ""}

    *: RESET

    C: RUN "RETURN 1 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "w"}

    # reader fails now with Neo.ClientError.Security.TokenExpired => this connection should also be re-authenticated
----
    A: HELLO {"user_agent": "*", "[routing]": "*", "scheme": "basic", "principal": "neo5j", "credentials": "pass++", "[realm]": ""}

    *: RESET

    C: RUN "RETURN 2 AS n" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "w"}
}}

*: RESET
?: GOODBYE
