!: BOLT #VERSION#

A: HELLO {"{}": "*"}
A: LOGON {"scheme": "basic", #DRIVER_AUTH#, "[realm]": ""}
*: RESET

# optionally, run more LOGOFF/LOGON cycles, and/or dummy queries
{*
    {{
        A: LOGOFF
        A: LOGON {"scheme": "basic", #VERIFY_AUTH#, "[realm]": ""}
    ----
        C: RUN {"U": "*"} "*" "*"
        S: SUCCESS {"fields": ["n"]}
        C: PULL {"n": {"Z": "*"}}
        S: RECORD [1]
           SUCCESS {"type": "r"}
    }}
    *: RESET
*}

?: GOODBYE
