!: BOLT #VERSION#

A: HELLO {"{}": "*"}
A: LOGON {"scheme": "basic", #DRIVER_AUTH#, "[realm]": ""}
*: RESET

C: ROUTE {"{}": "*"} [] {"{}": {"db": "system"}}
S: SUCCESS {"rt": {"ttl": 1000, "db": "system", "servers": [{"addresses": ["#HOST#:9000"], "role":"ROUTE"}, {"addresses": ["#HOST#:9010"], "role":"READ"}, {"addresses": ["#HOST#:9020"], "role":"WRITE"}]}}

*: RESET

IF: '''#DRIVER_AUTH#''' == '''#VERIFY_AUTH#'''
{?
    A: LOGOFF
    A: LOGON {"scheme": "basic", #VERIFY_AUTH#, "[realm]": ""}
    *: RESET
?}
ELSE:
{{
    A: LOGOFF
    A: LOGON {"scheme": "basic", #VERIFY_AUTH#, "[realm]": ""}
    *: RESET
}}

C: ROUTE {"{}": "*"} [] {"{}": {"db": "system"}}
S: FAILURE {"code": "#ERROR#", "message": "These are not the credentials you're looking for."}
   <EXIT>
