!: BOLT #VERSION#

A: HELLO {"{}": "*"}
A: LOGON {"scheme": "basic", "principal": "neo4j", "credentials": "pass", "[realm]": ""}
*: RESET

# warmup query
C: RUN {"U": "*"} "*" "*"
S: SUCCESS {"fields": ["n"]}
C: PULL {"n": {"Z": "*"}}
S: RECORD [1]
   SUCCESS {"type": "r"}

{{
    A: LOGOFF
    C: LOGON {"scheme": "basic", "principal": "neo5j", "credentials": "pass++", "[realm]": ""}
----
    C: RUN {"U": "*"} "*" "*"
}}

S: FAILURE {"code": "#ERROR#", "message": "These are not the credentials you're looking for."}
   <EXIT>
