!: BOLT 4.4
!: ALLOW RESTART

C: HELLO {"{}": "*"}
S: SUCCESS {"server": "Neo4j/4.4.1", "hints": {"connection.recv_timeout_seconds": 1}, "connection_id": "bolt-3"}
?: RESET
{{
    C: RUN "timeout" "*" "*"
    S: <SLEEP> 2
       SUCCESS {"fields": ["n"]}
    {?
        C: PULL {"n": "*"}
        S: RECORD [1]
           SUCCESS {"type": "r"}
    ?}
----
    C: RUN "in time" "*" "*"
    S: SUCCESS {"fields": ["n"]}
    {?
        C: PULL {"n": "*"}
        S: RECORD [1]
        S: SUCCESS {"type": "r"}
    ?}
    *: RESET
}}
?: GOODBYE
