!: BOLT 4.4

C: HELLO {"{}": "*"}
S: SUCCESS {"server": "Neo4j/4.4.1", "hints": {"connection.recv_timeout_seconds": 2}, "connection_id": "bolt-6"}
?: RESET
C: RUN "*" {} {}
S: <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   SUCCESS {"fields": ["n"]}
C: PULL {"n": "*"}
S: <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   RECORD [1]
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   SUCCESS {"type": "w"}
{*
    C: RESET
    S: <SLEEP> 1
       <NOOP>
       <SLEEP> 1
       <NOOP>
       <SLEEP> 1
       SUCCESS {}
*}
?: GOODBYE
