!: BOLT 4.3

C: HELLO "*"
S: SUCCESS {"server": "Neo4j/4.3.1", "hints": {"connection.recv_timeout_seconds": 2}, "connection_id": "bolt-5"}
C: BEGIN {}
S: <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   SUCCESS {}
C: RUN "*" "*" "*"
S: <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   SUCCESS {"fields": ["n"]}
C: PULL {"n": "*"}
S: <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   RECORD [1]
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   SUCCESS {"type": "r"}
C: COMMIT
S: <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   <NOOP>
   <SLEEP> 1
   SUCCESS {}
{*
    C: RESET
    S: <SLEEP> 1
       <NOOP>
       <SLEEP> 1
       <NOOP>
       <SLEEP> 1
       SUCCESS {}
*}
{?
    C: GOODBYE
    S: <EXIT>
?}
