!: BOLT 6.0

A: HELLO {"{}": "*"}
A: LOGON {"{}": "*"}

{*
    {{
        A: RESET
    ----
        A: BEGIN {"{}": "*"}
    ----
        C: RUN {"U": "*"} {"{}": "*"} {"{}": "*"}
        S: SUCCESS {"fields": ["x"], "qid": 1}
    ----
        {{
            C: PULL {"n": {"Z": "*"}, "[qid]": -1}
        ----
            C: PULL {"n": {"Z": "*"}, "qid": 1}
        ----
            C: DISCARD {"n": {"Z": "*"}, "[qid]": -1}
        ----
            C: DISCARD {"n": {"Z": "*"}, "qid": 1}
        }}
        S: RECORD [1]
        S: SUCCESS {"type": "r"}
    ----
        A: COMMIT
    ----
        A: ROLLBACK
    }}
*}

?: GOODBYE
