!: BOLT #VERSION#

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "#USER_AGENT#" #ROUTING#}
S: SUCCESS {"server": "#SERVER_AGENT#", "connection_id": "bolt-123456789"}
*: RESET

C: BEGIN {"db": "adb"}
S: SUCCESS {}
C: RUN "RETURN 1 as n" {} {}
S: SUCCESS {"fields": ["n"]}
{{
    C: PULL {"n": 1000}
    S: RECORD [1]
----
    C: DISCARD {"n": -1}
}}
S: SUCCESS {"type": "r"}
C: ROLLBACK
S: FAILURE {"code": "Neo.TransientError.General.DatabaseUnavailable", "message": "Unable to rollback"}
+: RESET

?: GOODBYE
