!: BOLT 4.4
!: ALLOW CONCURRENT

A: HELLO {"{}": "*"}
*: RESET
{{
    C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx42"]}
    S: SUCCESS {}
    C: RUN "MATCH (n) RETURN n.name AS name" {} {}
    S: SUCCESS {"fields": ["name"]}
    C: PULL {"n": 1000}
    S: SUCCESS {}
    C: COMMIT
    S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx4242"}
    *: RESET
    {?
        C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx4242"]}
        S: SUCCESS {}
        C: RUN "MATCH (n) RETURN n.name AS name" {} {}
        S: SUCCESS {"fields": ["name"]}
        C: PULL {"n": 1000}
        S: SUCCESS {}
        C: COMMIT
        S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx424242"}
        *: RESET
    ?}
----
    C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx4242"]}
    S: SUCCESS {}
    C: RUN "MATCH (n) RETURN n.name AS name" {} {}
    S: SUCCESS {"fields": ["name"]}
    C: PULL {"n": 1000}
    S: SUCCESS {}
    C: COMMIT
    S: SUCCESS {"bookmark": "neo4j:bookmark:v1:tx424242"}
    *: RESET
}}
?: GOODBYE
