!: BOLT #VERSION#
!: AUTO RESET
!: AUTO GOODBYE
!: ALLOW CONCURRENT

C: HELLO {"scheme": "basic", "credentials": "c", "principal": "p", "user_agent": "007", "routing": #HELLO_ROUTINGCTX# #EXTRA_HELLO_PROPS#}
S: SUCCESS {"server": "Neo4j/4.0.0", "connection_id": "bolt-123456789"}
{*
    C: RESET
    S: SUCCESS {}
*}
{*
    C: ROUTE #ROUTINGCTX# [] null
    S: SUCCESS { "rt": { "ttl": 1000, "servers": [{"addresses": ["#HOST#:9001"], "role":"ROUTER"}, {"addresses": ["#HOST#:9001"], "role":"READER"}, {"addresses": ["#HOST#:9001"], "role":"WRITE"}]}}
    {*
        C: RESET
        S: SUCCESS {}
    *}
*}
C: BEGIN {}
S: SUCCESS {}
{{
    C: RUN "RETURN 1" {} {}
    S: FAILURE {"code": "#ERROR#", "message": "<whatever>"}
    {?
        C: PULL "*"
        S: IGNORED
    ?}
    {+
        C: RESET
        S: SUCCESS {}
    +}
----
    C: RUN "RETURN 2" {} {}
    S: SUCCESS {"fields": ["1"]}
    C: PULL "*"
    S: RECORD [1]
       SUCCESS {"type": "r"}
    C: COMMIT
    S: SUCCESS {}
    {*
        C: RESET
        S: SUCCESS {}
    *}
}}
{*
    C: ROUTE #ROUTINGCTX# [] null
    S: SUCCESS { "rt": { "ttl": 1000, "servers": [{"addresses": ["#HOST#:9001"], "role":"ROUTER"}, {"addresses": ["#HOST#:9001"], "role":"READER"}, {"addresses": ["#HOST#:9001"], "role":"WRITE"}]}}
    {*
        C: RESET
        S: SUCCESS {}
    *}
*}
