!: BOLT 4.4
A: HELLO {"{}": "*"}
*: RESET

C: BEGIN {"{}": "*"}
S: SUCCESS {}
C: RUN "*" "*" "*"
S: SUCCESS {"fields": ["n"]}

# Pipelining driver: pipelined PULL
# Non-pipelining driver: result.next
C: PULL {"n": 2}
S: RECORD [1]
   RECORD [2]
   SUCCESS {"has_more": true}
{{
    # Pipelining driver
    # result.next
    C: PULL {"n": 2}
    S: RECORD [3]
       RECORD [4]
       SUCCESS {"has_more": true}
    # result.list
    C: PULL {"n": -1}
    S: RECORD [5]
----
    # Non-pipelining driver
    # result.list
    C: PULL {"n": -1}
    S: RECORD [3]
       RECORD [4]
       RECORD [5]
}}
S: SUCCESS {}

C: COMMIT
S: SUCCESS {"bookmark": "bm"}

*: RESET
?: GOODBYE
