!: BOLT 4.4

A: HELLO {"{}": "*"}
*: RESET
C: BEGIN {}
S: SUCCESS {}
C: RUN "CYPHER" {} {}
S: SUCCESS {"fields": ["x"], "qid": 1}
C: PULL {"n": 1, "[qid]": 1}
S: RECORD ["1_1"]
   SUCCESS {"has_more": true}
{{
    C: PULL {"n": 1, "[qid]": 1}
    S: RECORD ["1_2"]
       SUCCESS {"has_more": true}
    C: RUN "CYPHER NESTED" {} {}
    S: SUCCESS {"fields": ["x"], "qid": 2}
    {{
        C: PULL {"n": 1, "[qid]": 2}
        S: RECORD ["2_1"]
           SUCCESS {"has_more": true}
        C: PULL {"n": -1, "[qid]": 2}
        S: RECORD ["2_2"]
    ----
        C: PULL {"n": -1, "[qid]": 2}
        S: RECORD ["2_1"]
           RECORD ["2_2"]
    }}
    S: SUCCESS {}
    C: PULL {"n": 1, "qid": 1}
    S: RECORD ["1_3"]
       SUCCESS {}
    C: RUN "CYPHER NESTED" {} {}
    S: SUCCESS {"fields": ["x"], "qid": 3}
    {{
        C: PULL {"n": 1, "[qid]": 3}
        S: RECORD ["3_1"]
           SUCCESS {"has_more": true}
        C: PULL {"n": -1, "[qid]": 3}
        S: RECORD ["3_2"]
    ----
        C: PULL {"n": -1, "[qid]": 3}
        S: RECORD ["3_1"]
           RECORD ["3_2"]
    }}
    S: SUCCESS {}
    C: RUN "CYPHER NESTED" {} {}
    S: SUCCESS {"fields": ["x"], "qid": 4}
    {{
        C: PULL {"n": 1, "[qid]": 4}
        S: RECORD ["4_1"]
           SUCCESS {"has_more": true}
        C: PULL {"n": -1, "[qid]": 4}
        S: RECORD ["4_2"]
    ----
        C: PULL {"n": -1, "[qid]": 4}
        S: RECORD ["4_1"]
           RECORD ["4_2"]
    }}
    S: SUCCESS {}
----
    C: RUN "CYPHER NESTED" {} {}
    S: SUCCESS {"fields": ["x"], "qid": 2}
    {{
        C: PULL {"n": 1, "[qid]": 2}
        S: RECORD ["2_1"]
           SUCCESS {"has_more": true}
        C: PULL {"n": -1, "[qid]": 2}
        S: RECORD ["2_2"]
    ----
        C: PULL {"n": -1, "[qid]": 2}
        S: RECORD ["2_1"]
           RECORD ["2_2"]
    }}
    S: SUCCESS {}
    C: PULL {"n": 1, "qid": 1}
    S: RECORD ["1_2"]
       SUCCESS {"has_more": true}
    C: RUN "CYPHER NESTED" {} {}
    S: SUCCESS {"fields": ["x"], "qid": 3}
    {{
        C: PULL {"n": 1, "[qid]": 3}
        S: RECORD ["3_1"]
           SUCCESS {"has_more": true}
        C: PULL {"n": -1, "[qid]": 3}
        S: RECORD ["3_2"]
    ----
        C: PULL {"n": -1, "[qid]": 3}
        S: RECORD ["3_1"]
           RECORD ["3_2"]
    }}
    S: SUCCESS {}
    C: PULL {"n": 1, "qid": 1}
    S: RECORD ["1_3"]
       SUCCESS {}
    C: RUN "CYPHER NESTED" {} {}
    S: SUCCESS {"fields": ["x"], "qid": 4}
    {{
        C: PULL {"n": 1, "[qid]": 4}
        S: RECORD ["4_1"]
           SUCCESS {"has_more": true}
        C: PULL {"n": -1, "[qid]": 4}
        S: RECORD ["4_2"]
    ----
        C: PULL {"n": -1, "[qid]": 4}
        S: RECORD ["4_1"]
           RECORD ["4_2"]
    }}
    S: SUCCESS {}
}}
C: COMMIT
S: SUCCESS {"bookmark": "bm"}
*: RESET
?: GOODBYE
