!: BOLT 4.4

A: HELLO {"{}": "*"}
*: RESET
C: RUN "RETURN 1 AS n" {} {}
S: SUCCESS {"fields": ["1"]}
{{
    C: PULL {"n": {"Z": "1"}}
    S: RECORD [1]
       SUCCESS {"has_more": true}
   {?
        C: PULL {"n": {"Z": "*"}}
        S: RECORD [2]
           SUCCESS {"type": "r"}
   ?}
----
    C: PULL {"n": {"Z": "*"}}
    S: RECORD [1]
       RECORD [2]
       SUCCESS {"type": "r"}
}}
*: RESET
?: GOODBYE
